version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctors
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/doctors_db
      - SPRING_DATASOURCE_USERNAME=******
      - SPRING_DATASOURCE_PASSWORD=****
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "0000:0000"

  postgres:
    image: postgres:latest
    container_name: doctors_db
    environment:
      - POSTGRES_USER=******
      - POSTGRES_PASSWORD=****
      - POSTGRES_DB=doctors_db
    ports:
      - "0000:0000"
    volumes:
      - myVolume:/var/lib/postgresql/data

volumes:
  myVolume: