version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctors
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:----/*
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8787:0000"

  postgres:
    image: postgres:latest
    container_name: doctors_db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=*
    ports:
      - "0:0"
    volumes:
      - myVolume:/var/lib/postgresql/data

volumes:
  myVolume: